### PR TITLE
Find latest compatible version when checking compatibility

### LINKED ISSUE #9: bundle_report indicates no compatibility with given Rails version despite there is a compatible one
Hello.

I am using the `next_rails` gem to walk me through the easiest paths to upgrade our codebase.

I had the following dependencies:

```
gem 'rails',                          '4.2.11.3'
gem 'coffee-rails',                 '4.0.1'
```

When running `bundle exec bundle_report compatibility --rails-version=5.0.0` I got:

```
=> Incompatible with Rails 5.0.0 (with no new compatible versions):
These gems will need to be removed or replaced before upgrading to Rails 5.0.0.
coffee-rails 4.0.1 - new version, 5.0.0, is not compatible with Rails 5.0.0
15 gems incompatible with Rails 5.0.0
```

However, [version 4.1.1](https://github.com/rails/coffee-rails/blob/master/CHANGELOG.md#411-december-18-2015) is compatible with Rails 5.

I am wondering if improving this report to try find the bare minimum version that's compatible with Rails 5 is possible or is out of scope of this gem.

Regards, Matias.

### PR DESCRIPTION
**Pull request by arielj**
- [x] Add an entry to `CHANGELOG.md` that links to this PR under the "main (unreleased)" heading.

**Description:**

This PR changes how we check the compatibility of gems. Currently, if the current version of a gem is not compatible with the desired Rails version, we check if the latest available version of that gem is compatible with Rails.

This is a problem, because the latest version may not be compatible with the desired Rails version, but there might be other versions between the current and the latest that are compatible.

This PR updates the compatibility check to check all versions from the latest to the current until it finds a compatible version.

**How I tested this:**

I really don't know how to add an automated test for this, it relies a lot on external data.

What I did to test this was:
- created a new Rails 4.2.11 app
- changed the version of coffee-rails from 4.1.0 to 4.0.1
- added `next_rail` to the gemfile
- ran `bundle exec bundle_report compatibility --rails-version=5.0.0`

Before this fix:

```
$ bundle exec bundle_report compatibility --rails-version=5.0.0
=> Incompatible with Rails 5.0.0 (with new versions that are compatible):
These gems will need to be upgraded before upgrading to Rails 5.0.0.

rails-dom-testing 1.0.9 - upgrade to 2.0.3

=> Incompatible with Rails 5.0.0 (with no new compatible versions):
These gems will need to be removed or replaced before upgrading to Rails 5.0.0.

coffee-rails 4.0.1 - new version, 5.0.0, is not compatible with Rails 5.0.0

2 gems incompatible with Rails 5.0.0
```

After this fix:

```
$ bundle exec bundle_report compatibility --rails-version=5.0.0
=> Incompatible with Rails 5.0.0 (with new versions that are compatible):
These gems will need to be upgraded before upgrading to Rails 5.0.0.

coffee-rails 4.0.1 - upgrade to 4.2.2
rails-dom-testing 1.0.9 - upgrade to 2.0.3

2 gems incompatible with Rails 5.0.0
```

As expected from the report.

Closes #9 

I will abide by the [code of conduct](https://github.com/fastruby/next_rails/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by kindoflew** [comment]
hi @cleicar, can you review this when you have a chance? thanks!

**Comment by kindoflew** [comment]
ping @cleicar :shipit:

**Comment by kindoflew** [comment]
hello @KattKit! can you review this when you have a chance? thanks!

**Comment by bronzdoc** [comment]
I will QA this tomorrow :shipit:  ping me if I don't :shipit:

**Comment by kindoflew** [comment]
@bronzdoc :shipit:

**Review by bronzdoc — APPROVED** [review]

**Pull request merged**
