### PR TITLE
Fix for up_to_date? method

### PR DESCRIPTION
**Pull request by dkhan**
`bundle_report outdated` is currently failing with "undefined local variable or method `latest_version'".
We need to define latest_version method to filter out up-to-date gems.

### CODE REVIEW

**Comment by rishijain** [comment]
Yes, I faced the same issue 2 days ago on a project I was working on.
But on a different project, I did not got the error. 

So I got a little confused, as in, was it the difference in projects that triggered or something else.
I am using the same version of next_rails in both the projects.

**Comment by dkhan** [comment]
Weird. It must happen with any project on `bundle_report outdated` unless the project does not have any gems...

**Comment by rishijain** [comment]
Yes, the other project definitely has lot of gems. So not sure why it happened.
Good thing is it is still breaking for me for the other project, I will try to dig deeper and post here if I find anything.

**Comment by rishijain** [comment]
hey @dkhan can you please resolve conflicts?

**Comment by rishijain** [comment]
Hey @dkhan to complete our conversation above, I did check in those 2 projects and it was because I was on 2 different versions of the gem.

So your change fix this as it adds back the method that was accidentally deleted in a older PR. 
As soon as you resolve the conflicts, I will be able to review and merge. Thanks for figuring out and sending the PR. :)

**Comment by ckhall** [comment]
any status on this getting reviewed/merged/released soon?

**Comment by arielj** [comment]
hey @dkhan can you check the conflicts in the PR? thanks!

**Comment by dkhan** [comment]
Should be resolved now. Sorry for the delay.

**Review by rishijain — APPROVED** [review]

**Comment by rishijain** [comment]
Hey @dkhan thank you for the work on this PR. :green_heart:

**Pull request merged**
